#ifndef CONFIG_H
#define CONFIG_H

#define MAX_STRING_SIZE                 4096
#define WILDCARD_FILE_READ_BUFFER_SIZE  2048
#define ENV_WILDCARD_FILE_PATH          "WILDCARD_MUTATOR_FILE"
#define ENV_WILDCARD_DEBUG_MODE         "WILDCARD_MUTATOR_DEBUG_MODE"

#endif